apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-spring-boot-namespace
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
  SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: "20000"
  SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: "5"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"

