apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: my-spring-boot-namespace
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM= # 
  SPRING_DATASOURCE_PASSWORD: d3AxMjM=     # 

